### ISSUE TITLE
OnlineStats is about to break your code

### ISSUE THREAD

**Issue by joshday** [tkf/LyapunovExponents.jl#6]
Hi there,

OnlineStats is getting some design changes that will break your code and I wanted to give you a heads up.  

Also, just glancing at the code, I think OnlineStats already has what you're calling `VecMean` and `VecVariance` via the `Group` type.  `VecMean(p)` would become `p * Mean()` and `VecVariance(p)` would become `p * Variance()`.

**Comment by joshday** [comment]
I wanted to make a PR so you could easily update to the changes, but I can't install LyapunovExponents due to an infeasible version for DataFrames.  

The biggest change in OnlineStats is that stats no longer need to be wrapped in a Series, as they should keep track of their own number of observations and (if necessary) weight.

**Comment by tkf** [comment]
Thank you for your kind ping and code review and suggestion!

I'm doing most of the development in `dev` branch which is way ahead of `master`, which in turn, is a way ahead of the release, at the moment.  So the repo is too messy for a PR now...

`Group` sounds like a very handy combinator.  I wonder if it works nicely with large number of `Mean` stats (e.g., `p` around 100 to 10000).  I mean, struct-of-vectors is better than vector-of-structs in performance, typically.  Also, I don't know how large tuples behave in Julia.  I haven't done any benchmark, but I wonder if it makes sense to still keep `Vec*` versions.  I obviously have to do benchmarks, but did you consider the case that there are moderately large number (> 100, say) of parallel streams?  Did you do benchmarks to conclude that the approach like `Group` scales well?

**Comment by joshday** [comment]
I'm also unfamiliar with how large tuples behave, but I just changed `Group` to allow storing either vectors or tuples.  Not sure of the data sizes you're working with, but here's a quick timing:

```julia
julia> x = randn(1000, 10^5);

julia> @time fit!(Group([Mean() for i in 1:1000]), eachcol(x));
  0.159630 seconds (9.80 k allocations: 522.098 KiB)
```

**Comment by tkf** [comment]
Thanks. Maybe I'll do some benchmarks. If I find a domain that my `Vec*` versions are faster, do you want a PR to add them to OnlineStats.jl?  They can be useful for other people.
